apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: service
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-rabbitmq
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: {{ .Values.orders.db.user }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ .Values.orders.db.password }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: "rabbitmq"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "orders-rabbitmq:5672"
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: {{ .Values.orders.db.provider }}
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "orders-postgresql:5432"
  RETAIL_ORDERS_PERSISTENCE_NAME: {{ .Values.orders.db.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgresql
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: orders-rabbitmq
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: service
spec:
  replicas: {{ .Values.orders.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/component: service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: service
    spec:
      serviceAccountName: orders
      securityContext:
        fsGroup: 1000
      containers:
        - name: orders
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.orders.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
          envFrom:
            - secretRef:
                name: orders-rabbitmq
            - secretRef:
                name: orders-db
            - configMapRef:
                name: orders
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.orders.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-postgresql
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  serviceName: orders-postgresql
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.global.imageRegistry }}/public.ecr.aws/docker/library/postgres:16.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: {{ .Values.orders.db.name | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: RETAIL_ORDERS_PERSISTENCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-db
                  key: RETAIL_ORDERS_PERSISTENCE_PASSWORD
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-rabbitmq
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  serviceName: orders-rabbitmq
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.orders.rabbitmq.image }}"
          imagePullPolicy: IfNotPresent
          ports:
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: http
            containerPort: 15672
            protocol: TCP
          volumeMounts:
          - name: data
            mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: data
        emptyDir: {}