global:
  owner: retail-store-sample
  managedBy: Helm
  imageRegistry: "" # ĐỂ TRỐNG: để các service bổ trợ (DB, MQ) tự dùng registry mặc định của chúng

# --- UI SERVICE ---
ui:
  replicaCount: 1
  image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.0.1-amd64 # ĐẦY ĐỦ ĐƯỜNG DẪN
  theme: default
  searchEnabled: "false"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 128m
      memory: 512Mi

# --- CATALOG SERVICE ---
catalog:
  replicaCount: 1
  image: public.ecr.aws/aws-containers/retail-store-sample-catalog:1.6.1 # ĐẦY ĐỦ ĐƯỜNG DẪN
  searchEnabled: "false"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 256m
      memory: 256Mi
  db:
    provider: mysql
    name: catalog
    user: "Y2F0YWxvZw==" 
    password: "U2pvOXA0aXRQZXNVWGk1Sw==" 
    rootPassword: "my-secret-pw"

# --- CARTS SERVICE ---
carts:
  replicaCount: 1
  image: public.ecr.aws/aws-containers/retail-store-sample-cart:1.6.1 # ĐẦY ĐỦ ĐƯỜNG DẪN
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 512Mi
  dynamodb:
    image: aws-dynamodb-local/aws-dynamodb-local:1.25.1 # Giữ nguyên cấu trúc mặc định của chart
    tableName: Items
    createTable: "true"
    awsAccessKey: "key"
    awsSecretKey: "secret"

# --- ORDERS SERVICE ---
orders:
  replicaCount: 1
  image: public.ecr.aws/aws-containers/retail-store-sample-orders:1.6.1 # ĐẦY ĐỦ ĐƯỜNG DẪN
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 512Mi
  db:
    provider: postgres
    name: orders
    user: "b3JkZXJz" 
    password: "WGh5TW01UUo2ZUlWdW5Tdw==" 
    rootPassword: "my-secret-pw"
  rabbitmq:
    image: docker/library/rabbitmq:3-management # Chỉ ghi phần đuôi, để chart tự nối registry mặc định

# --- CHECKOUT SERVICE ---
checkout:
  replicaCount: 1
  image: public.ecr.aws/aws-containers/retail-store-sample-checkout:1.6.1 # ĐẦY ĐỦ ĐƯỜNG DẪN
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 128m
      memory: 256Mi
  redis:
    image: docker/library/redis:6.0-alpine # Chỉ ghi phần đuôi, để chart tự nối registry mặc định

