apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base/catalog
  - ../../base/cart
  - ../../base/orders
  - ../../base/checkout
  - ../../base/ui
commonLabels:
  environment: dev
images:
  - name: cart
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/cart
    newTag: latest
  - name: catalog
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/catalog
    newTag: test-tag-1234
  - name: checkout
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/checkout
    newTag: test-tag-1235
  - name: orders
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/orders
    newTag: c18ab7e3a90a47863e6b1ec1c23ee272f719d8fc
  - name: ui
    newName: 248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/ui
    newTag: latest
